# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code Crush
email: codecrushme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Podcast for Developers with Short Attention Spans
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: "Julie & Kiana"
twitter_username: crushcode
github_username:  codecrushed
repository: "codecrushed/codecrushed.github.io"
remote_theme: "mmistakes/minimal-mistakes"
teaser: assets/images/code_crush_banner.png
header:
  teaser: /assets/images/code_crush_banner.png
search: true
og_image: assets/images/code_crush_logo.png
defaults:
  - scope:
      path: ""
    values:
      header:
        image: /assets/images/code_crush_banner.png
        caption: "With Kiana and Julie"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      related: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
